gui:
  language: "en"
  showRandomTip: false
  showCommandLog: false
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  pull:
    rebase: true
  autoFetch: true
  fetchAll: true
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
